name : "测试推送项目"
on : push
jobs:
    myjob1:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: ls
    myjob2:
        runs-on: ubuntu-latest
        steps:
        - run: python -V
    myjob3:
        runs-on: ubuntu-latest
        name: "Get URL"
        steps:
        - run: curl ifconfig.me

     